# Generated by Django 4.0.6 on 2022-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('days', models.CharField(max_length=20)),
                ('starttime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('location', models.CharField(max_length=15)),
            ],
        ),
    ]
